### ISSUE TITLE
Problem to notify Quantunleap

### ISSUE THREAD

**Issue by alvaroo278** [orchestracities/ngsi-timeseries-api#719]
**Description Issue**
I am trying to send a notification from Orion-LD to Quantumleap, but nothing arrives in the QL service. To check that Orion is notifying correctly, I am using a duplicate subscription that has as an endpoint a service echo (Webhook). I am using Kubernetes (ArgoCD) to configure and control the service.

**Orion-LD configuration**

```  
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orion
  name: orion
spec:
  ports:
  - name: http
    port: 1026
    protocol: TCP
    targetPort: 1026
  selector:
    app: orion

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion
  template:
    metadata:
      labels:
        app: orion
    spec:
      containers:
        - command: ["orionld"]
          args: ["-fg", "-multiservice", "-ngsiv1Autocast", "-dbhost", "mongodb",
               "-logLevel", "DEBUG"]
          image: "fiware/orion-ld:1.0.1"
          imagePullPolicy: IfNotPresent
          name: orion
          ports:
          - containerPort: 1026
            name: http

```

**Quantumleap configuration**

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: quantumleap
  name: quantumleap
spec:
  ports:
  - name: http
    port: 8668
    protocol: TCP
    targetPort: 8668
  selector:
    app: quantumleap

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantumleap
  labels:
    app: quantumleap
  annotations:
    # Tell Reloader to bounce the Argo CD server whenever the SSO config
    # and built-in admin credentials change.
    secret.reloader.stakater.com/reload: "postgres-users"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantumleap
  template:
    metadata:
      labels:
        app: quantumleap
    spec:
      initContainers:
        - name: quantumleap-pg-init
          image: "smartsdk/quantumleap-pg-init:0.7.6"
          imagePullPolicy: IfNotPresent
          env:
          - name: PG_HOST
            value: postgres
          - name: PG_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-users
                key: postgres.password
          - name: QL_DB_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-users
                key: quantumleap.password
          - name: QL_DB_INIT_DIR
            value: /db-init
          volumeMounts:
          - name: db-init
            mountPath: /db-init
      containers:
        - image: "orchestracities/quantumleap:0.8.3"
          imagePullPolicy: IfNotPresent
          name: quantumleap          
          ports:
          - containerPort: 8668
            name: http
          env:
          - name: POSTGRES_HOST
            value: "postgres"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USE_SSL
            value: "False"
          - name: POSTGRES_DB_NAME
            value: "quantumleap"
          - name: POSTGRES_DB_USER
            value: "quantumleap"
          - name: POSTGRES_DB_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-users
                key: quantumleap.password
          - name: CRATE_HOST
            value: "crate"
          - name: CRATE_PORT
            value: "4200"
          - name: QL_CONFIG
            value: /config/db-routing.yaml
          - name: DEBUG
            value: "true"
          volumeMounts:
          - name: db-routing
            mountPath: /config
      volumes:
        - name: db-routing
          configMap:
            name: db-routing
        - name: db-init
          emptyDir: {}

```
Regarding the quantumleap images I use, if I use as initializer the orchestracities image (whatever version I use), the pod doesn't start.

**Orion-LD subscription**

```
{
    "id": "urn:ngsi-ld:Subscription:63dbab3998657c37179501a9",
    "type": "Subscription",
    "description": "Notify alert",
    "entities": [
      {
        "type": "AirQualityAlert"
      }
    ],
    "notification": {
      "attributes": [
        "analysis",
        "dateIssued",
        "prediction"
      ],
      "format": "normalized",
      "endpoint": {
        "uri": "http://192.168.1.18/quantumleap/v2/notify",
        "accept": "application/json"
      }
    },
    "@context": "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
  }
```

On the other hand, if I enter the logs of the quantumleap pod, it appears empty:
``` kubectl logs -f {id-pod}````

I have also tried to manually notify Quantumleap and I get a timeout error when making the request

**Post Request**

```
curl --location --request POST 'http://192.168.1.18/quantumleap/v2/notify' \
--header 'ngsild-tenant: airqualityalert' \
--header 'fiware-servicepath: /' \
--header 'Content-Type: application/json' \
--data-raw '{
  "id": "urn:ngsi-ld:Notification:63e274e0cb0b200efafa99ee",
  "type": "Notification",
  "subscriptionId": "urn:ngsi-ld:Subscription:63dbaa4998657c37179501a3",
  "notifiedAt": "2023-02-07T15:57:20.549Z",
  "data": [
    {
      "id": "urn:ngsi-ld:AirQualityAlert:Out.3857499894.1",
      "type": "AirQualityAlert",
      "analysis": {
        "type": "Property",
        "value": "good"
      },
      "prediction": {
        "type": "Property",
        "value": "good"
      },
      "dateIssued": {
        "type": "Property",
        "value": {
          "type": "DateTime",
          "value": "2023-02-07T15:57:20.519Z"
        }
      }
    }
  ]
}'
```
